### ISSUE TITLE
Multiple namespaces, some missing in PSR-4 autoload

### ISSUE THREAD

**Issue by degerstrom** [JorgenSolli/contact-manager-api#1]
I see at least four namespaces in use in your code:

```
EcoOnline\ContactManagerApi\
EcoOnline\ContactManager\
EcoOnline\EcoPackage\
Kronos\
```

But only the first one is autoloaded in the `composer.json` file.

You should consolidate into **one** namespace, and avoid overwriting the `EcoOnline\EcoPackage` namespace, it will probably lead to collisions.

You might also reference [this page](https://ecoonline.atlassian.net/l/c/0MYSJw7o) to learn how to run static analysis on your code.

**Comment by degerstrom** [comment]
@JorgenSolli I was unable to assign this issue to you, but tagging you here so you're notified.

**Comment by JorgenSolli** [comment]
@degerstrom These issues should be resolved now.
